### ISSUE TITLE
Specs falhando no master

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#69]
``` sh
apps (master) > rspec
..........................................................F...............................................F.....................................**................................................

Pending:
  AppsController GET index when filtering app by category should return correct number of apps
    # Temporarily disabled with xit
    # ./spec/controllers/apps_controller_spec.rb:36
  AppsController GET index when filtering app by category should return corret type of apps
    # Temporarily disabled with xit
    # ./spec/controllers/apps_controller_spec.rb:42

Failures:

  1) App has many categories should not destroy app when associated categories are destroyed
     Failure/Error: @category = Category.create(name: "Rock School")
     NoMethodError:
       undefined method `kind' for #<Category:0x007ff62a437ee8>
     # ./spec/models/app_spec.rb:70:in `block (3 levels) in <top (required)>'

  2) Category 
     Failure/Error: it { should respond_to(:kind) }
       expected #<Category id: nil, name: nil, created_at: nil, updated_at: nil> to respond to :kind
     # ./spec/models/category_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 1 minute 13.66 seconds
194 examples, 2 failures, 2 pending

Failed examples:

rspec ./spec/models/app_spec.rb:73 # App has many categories should not destroy app when associated categories are destroyed
rspec ./spec/models/category_spec.rb:5 # Category 

Randomized with seed 49712
```

**Comment by embs** [comment]
Rodei aqui e não houve falhas. @guiocavalcanti, verifica isso aí e fecha se não falhar nada, por gentileza. Muito provavelmente (depois do merge front-end into master) qualquer erro nas specs já foi sanado.

**Comment by guiocavalcanti** [comment]
Testei novamente com o master depois do merge:

``` sh
apps (master) > rspec
......................................................................F..............F**...............................................................................................F.......

Pending:
  AppsController GET index when filtering app by category should return correct number of apps
    # Temporarily disabled with xit
    # ./spec/controllers/apps_controller_spec.rb:32
  AppsController GET index when filtering app by category should return corret type of apps
    # Temporarily disabled with xit
    # ./spec/controllers/apps_controller_spec.rb:38

Failures:

  1) Category 
     Failure/Error: it { should respond_to(:kind) }
       expected #<Category id: nil, name: nil, created_at: nil, updated_at: nil> to respond to :kind
     # ./spec/models/category_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) AppsController GET index when assigning variables assigns @categories variable
     Failure/Error: assigns(:categories).should == Category.all
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Unknown column 'categories.kind' in 'where clause': SELECT `categories`.* FROM `categories`  WHERE `categories`.`kind` = 'Nível'
     # ./spec/controllers/apps_controller_spec.rb:17:in `block (4 levels) in <top (required)>'

  3) App has many categories should not destroy app when associated categories are destroyed
     Failure/Error: @category = Category.create(name: "Rock School")
     NoMethodError:
       undefined method `kind' for #<Category:0x007fc940a14238>
     # ./spec/models/app_spec.rb:70:in `block (3 levels) in <top (required)>'

Finished in 1 minute 14.69 seconds
191 examples, 3 failures, 2 pending

Failed examples:

rspec ./spec/models/category_spec.rb:5 # Category 
rspec ./spec/controllers/apps_controller_spec.rb:16 # AppsController GET index when assigning variables assigns @categories variable
rspec ./spec/models/app_spec.rb:73 # App has many categories should not destroy app when associated categories are destroyed
```

**Comment by guiocavalcanti** [comment]
@embs o `rake db:prepare` funcionou. Coloca isso no README numa seção "Contributing"
